BOARD_TAG    = mega
BOARD_SUB    = atmega2560
#BOARD_SUB    = atmega1280
MONITOR_PORT = /dev/ttyACM0
#ARDUINO_DIR  = /where/you/installed/arduino-1.6.5
OPTIMIZATION_LEVEL = 0
#CFLAGS = -Wl,--section-start=.siminfo=0x900000
#CXXFLAGS = -fpermissive -Wl,--section-start=.siminfo=0x900000
#CXXFLAGS = -Wl,--section-start=.siminfo=0x900000
#NO_CORE = 1
#MCU=atmega1284
#F_CPU=16000000
include /usr/share/arduino/Arduino.mk
